language: python

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

python:
- 3.6
- 3.7
- 3.8

matrix:
  include:
  - python: 3.6
  - python: 3.7
  - python: 3.8

install:
- make init

script:
- make ci
